### ISSUE TITLE
Compatible for 1.17 but using java 17?

### ISSUE THREAD

**Issue by Herobrine2143** [adryd325/chat-lag-fix#1]
The game will not launch if Minecraft 1.17 uses java 17, it has to be java 16, otherwise it just crashes.

Mod Version 2.0.1

**Comment by adryd325** [comment]
1.0.0 was 1.17 compatible, i forgot to check with on 2.0.0

2.0.2 will have a dedicated 1.17 version

**Comment by adryd325** [comment]
the 1.17 version is working now
