### ISSUE TITLE
2.0.2 for 1.17.1 still needs Java 17

### ISSUE THREAD

**Issue by Youmiel** [adryd325/chat-lag-fix#2]
The mod version 2.0.2 still needs java 17, but Minecraft 1.17 crashed with "Java runtime mismatch" when I tried to launch the game with Java 17.

**Comment by adryd325** [comment]
I'll reupload the jar to modrinth, its just the metadata i forgot to update

**Comment by adryd325** [comment]
went and tested each version with their minimum java version
https://cdn.modrinth.com/data/fKi1znuF/versions/mc1.17.x-2.0.2/chatlagfix-1.17.1-2.0.2-java16.jar
this one works
