### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by GeefireMC** [adryd325/chat-lag-fix#5]
the creator of an alternate fix mod says that the API is not fixed (https://github.com/KosmX/non-blocking_chat/issues/1), in contradiction with what this mod's modrinth page says. I'm just looking for a quick clarification as to that.

**Comment by adryd325** [comment]
I've checked with debug logging enabled, it only fetches the block list once now, and there's no error after fetching the list. Before, when debug logging was enabled, it would show that the HTTP request failed. The mod may still help world load times or server join times as thats when the block list is usually fetched. I just don't want to give people the sense that the mod is actually doing something when it's not anymore.
![image](https://user-images.githubusercontent.com/48024900/149632642-fd118e02-f5a9-4d28-a8d9-05d9658a18c6.png)

**Comment by GeefireMC** [comment]
Thanks for the response.
